### ISSUE TITLE
Should Mirrors.h.TEMPLATE be Mirrors.h?

### ISSUE THREAD

**Issue by gashtal** [lordmulder/MUtilities#2]
The MSVC currently fails to compile due to missing `Mirrors.h` file. There is a `Mirrors.h.TEMPLATE` file under the `src` directory, and renaming that to `Mirrors.h` resolves the issue and allows the project to compile successfully. If this is intentional, it would be helpful to add bullet point about this in the build notes. Otherwise, renaming the `Mirrors.h.TEMPLATE` to `Mirrors.h` in the repository should allow the project to be compiled out of the box.

**Comment by lordmulder** [comment]
That is exactly the intended purpose.

You are supposed to provided your own `Mirrors.h` and the "template" is provided for that reason.
